//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEmlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emlak
    {
        public Emlak()
        {
            this.Durum = false;
        }
    
        public int Id { get; set; }
        public int ÜyeId { get; set; }
        public System.DateTime Tarih { get; set; }
        public decimal Fiyat { get; set; }
        public string Adres { get; set; }
        public int ŞehirId { get; set; }
        public bool Durum { get; set; }
        public int TipId { get; set; }
        public string Başlık { get; set; }
        public byte[] Görsel { get; set; }
    
        public virtual Üye Üye { get; set; }
        public virtual Şehir Şehir { get; set; }
        public virtual Tip Tip { get; set; }
    }
}
