//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEmlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konut : Emlak
    {
        public int Metrekare { get; set; }
        public string OdaBilgisi { get; set; }
        public string KatBilgisi { get; set; }
        public string IsıtmaSistemi { get; set; }
    }
}
