//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Arsa : Emlak
{
    public int Metrekare { get; set; }
    public bool İmarlı { get; set; }
}

public partial class Dükkan : Emlak
{
    public int Metrekare { get; set; }
    public bool Depo { get; set; }
}

public partial class Emlak
{
    public Emlak()
    {
        this.Durum = false;
    }

    public int Id { get; set; }
    public int ÜyeId { get; set; }
    public System.DateTime Tarih { get; set; }
    public decimal Fiyat { get; set; }
    public string Adres { get; set; }
    public int ŞehirId { get; set; }
    public bool Durum { get; set; }
    public int TipId { get; set; }
    public string Başlık { get; set; }
    public byte[] Görsel { get; set; }

    public virtual Üye Üye { get; set; }
    public virtual Şehir Şehir { get; set; }
    public virtual Tip Tip { get; set; }
}

public partial class Konut : Emlak
{
    public int Metrekare { get; set; }
    public string OdaBilgisi { get; set; }
    public string KatBilgisi { get; set; }
    public string IsıtmaSistemi { get; set; }
}

public partial class Şehir
{
    public Şehir()
    {
        this.Emlak = new HashSet<Emlak>();
    }

    public int Id { get; set; }
    public string İsim { get; set; }

    public virtual ICollection<Emlak> Emlak { get; set; }
}

public partial class Tip
{
    public Tip()
    {
        this.Emlak = new HashSet<Emlak>();
    }

    public int Id { get; set; }
    public string Ad { get; set; }

    public virtual ICollection<Emlak> Emlak { get; set; }
}

public partial class Üye
{
    public Üye()
    {
        this.EPostaDoğrulama = false;
        this.Emlak = new HashSet<Emlak>();
    }

    public int Id { get; set; }
    public string İsim { get; set; }
    public string EPosta { get; set; }
    public string Şifre { get; set; }
    public bool EPostaDoğrulama { get; set; }
    public System.DateTime ÜyelikTarihi { get; set; }

    public virtual ICollection<Emlak> Emlak { get; set; }
}
