//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEmlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Üye
    {
        public Üye()
        {
            this.EPostaDoğrulama = false;
            this.Emlak = new HashSet<Emlak>();
        }
    
        public int Id { get; set; }
        public string İsim { get; set; }
        public string EPosta { get; set; }
        public string Şifre { get; set; }
        public bool EPostaDoğrulama { get; set; }
        public System.DateTime ÜyelikTarihi { get; set; }
    
        public virtual ICollection<Emlak> Emlak { get; set; }
    }
}
